#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC4

GEN_C_SOURCE_CortexM0=\
	$(GEN_SOURCE_DIR)/CapSense_CSD.c\
	$(GEN_SOURCE_DIR)/CapSense_CSD_PM.c\
	$(GEN_SOURCE_DIR)/CapSense_CSD_INT.c\
	$(GEN_SOURCE_DIR)/CapSense_CSD_TunerHelper.c\
	$(GEN_SOURCE_DIR)/BLE.c\
	$(GEN_SOURCE_DIR)/BLE_gatt.c\
	$(GEN_SOURCE_DIR)/BLE_eventHandler.c\
	$(GEN_SOURCE_DIR)/BLE_HAL_INT.c\
	$(GEN_SOURCE_DIR)/BLE_HAL_PVT.c\
	$(GEN_SOURCE_DIR)/BLE_custom.c\
	$(GEN_SOURCE_DIR)/PrISM_1.c\
	$(GEN_SOURCE_DIR)/PrISM_1_PM.c\
	$(GEN_SOURCE_DIR)/PrISM_2.c\
	$(GEN_SOURCE_DIR)/PrISM_2_PM.c\
	$(GEN_SOURCE_DIR)/PrISM_Clock.c\
	$(GEN_SOURCE_DIR)/BLUE.c\
	$(GEN_SOURCE_DIR)/BLUE_PM.c\
	$(GEN_SOURCE_DIR)/RED.c\
	$(GEN_SOURCE_DIR)/RED_PM.c\
	$(GEN_SOURCE_DIR)/GREEN.c\
	$(GEN_SOURCE_DIR)/GREEN_PM.c\
	$(GEN_SOURCE_DIR)/User_Button.c\
	$(GEN_SOURCE_DIR)/User_Button_PM.c\
	$(GEN_SOURCE_DIR)/isr_button.c\
	$(GEN_SOURCE_DIR)/UART.c\
	$(GEN_SOURCE_DIR)/UART_SPI_UART.c\
	$(GEN_SOURCE_DIR)/UART_SPI_UART_INT.c\
	$(GEN_SOURCE_DIR)/UART_PM.c\
	$(GEN_SOURCE_DIR)/UART_UART.c\
	$(GEN_SOURCE_DIR)/UART_BOOT.c\
	$(GEN_SOURCE_DIR)/UART_UART_BOOT.c\
	$(GEN_SOURCE_DIR)/CapSense_CSD_SampleClk.c\
	$(GEN_SOURCE_DIR)/CapSense_CSD_SenseClk.c\
	$(GEN_SOURCE_DIR)/BLE_bless_isr.c\
	$(GEN_SOURCE_DIR)/UART_SCBCLK.c\
	$(GEN_SOURCE_DIR)/UART_tx.c\
	$(GEN_SOURCE_DIR)/UART_tx_PM.c\
	$(GEN_SOURCE_DIR)/UART_SCB_IRQ.c\
	$(GEN_SOURCE_DIR)/UART_rx.c\
	$(GEN_SOURCE_DIR)/UART_rx_PM.c\
	$(GEN_SOURCE_DIR)/cy_em_eeprom.c\
	$(GEN_SOURCE_DIR)/CyFlash.c\
	$(GEN_SOURCE_DIR)/CyLib.c\
	$(GEN_SOURCE_DIR)/cyPm.c\
	$(GEN_SOURCE_DIR)/cyutils.c\
	$(GEN_SOURCE_DIR)/CyDMA.c\
	$(GEN_SOURCE_DIR)/CyLFClk.c

GEN_ASM_SOURCE_CortexM0=\
	$(GEN_SOURCE_DIR)/CyBootAsmGnu.s

GEN_SEP_C_SOURCE_CortexM0=\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/Cm0Start.c

GEN_LIBS_CortexM0=\
	Export/ARM_GCC_Generic/BLE_v3_50/gccCyBLEStack_BLE_SOC_PERIPHERAL.a\
	Export/ARM_GCC_Generic/CapSense_CSD_P4_v2_60/CapsenseP4Library_GCC.a

