#!/bin/sh
# This script allows a 3rd party IDE to use cyelftool.exe to perform
# the post processing that is necessary to update the *.elf file
# generated by the linker into a complete memory image to use in
# programming the PSoC.
# NOTE: Please provide the path to the CyElfTool.
./Export/cyelftool -C "$1" --flash_row_size 256 --flash_size 262144 --flash_offset 0x00000000 
LAST_EXIT=$?
if [ $LAST_EXIT != 0 ]; then
    exit $LAST_EXIT
fi
